# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Oracle.SQLcl
PackageVersion: 26.3.0.260.1620
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: sqlcl/bin/sql.exe
UpgradeBehavior: install
ReleaseDate: 2026-09-29
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x86
  InstallerUrl: https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-26.3.0.260.1620.zip
  InstallerSha256: EB0DCA2BECC30E9AA1C700AE71E5DF6EFDE8A33D098D7D23405B6558BBB81A81
ManifestType: installer
ManifestVersion: 1.12.0
