# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Nefarius.DsHidMini
PackageVersion: 3.15.0
MinimumOSVersion: 10.0.17763.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ProductCode: '{25784100-B9AA-4205-8D54-CA53A16F7AC5}'
ReleaseDate: 2026-09-24
AppsAndFeaturesEntries:
- DisplayName: Nefarius DsHidMini Driver
  ProductCode: '{25784100-B9AA-4205-8D54-CA53A16F7AC5}'
  UpgradeCode: '{25784100-B9AA-4205-8D54-CA53717F6AC5}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Nefarius Software Solutions\DsHidMini'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nefarius/DsHidMini/releases/download/setup-v3.15.0/Nefarius_DsHidMini_Drivers_x64_arm64_v3.15.0.msi
  InstallerSha256: AD0DEAF88BD95699EEF2908477009B14E3857EABA66E042B1E24D5A561140292
- Architecture: arm64
  InstallerUrl: https://github.com/nefarius/DsHidMini/releases/download/setup-v3.15.0/Nefarius_DsHidMini_Drivers_x64_arm64_v3.15.0.msi
  InstallerSha256: AD0DEAF88BD95699EEF2908477009B14E3857EABA66E042B1E24D5A561140292
ManifestType: installer
ManifestVersion: 1.12.0
