# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: muquit.mailsend-go
PackageVersion: 1.0.13
PackageLocale: en-US
Publisher: muquit
PublisherUrl: https://www.muquit.com/
PublisherSupportUrl: https://github.com/muquit/mailsend-go/issues
Author: Muhammad Muquit
PackageName: mailsend-go
PackageUrl: https://github.com/muquit/mailsend-go
License: MIT
LicenseUrl: https://github.com/muquit/mailsend-go/blob/HEAD/LICENSE.txt
Copyright: Copyright © 2018-present muquit@muquit.com
CopyrightUrl: https://github.com/muquit/mailsend-go/blob/HEAD/LICENSE.txt
ShortDescription: A multi-platform command line tool to send mail via SMTP protocol
Moniker: mailsend-go
ReleaseNotes: |-
  This release fixes Issue #76.
  The options -printCerts and -verifyCert now take effect while sending
  mail, not just with -info. Added -verbose as a shortcut for
  -debug -printCerts -verifyCert together.
  No need to update unless you need certificate details or verification
  while sending mail.
  Please look at ChangeLog for details.
  The binaries are cross-compiled with
  go-xbuild-go
  Do not forget to check checksums of the archives before using.
  Thanks.
ReleaseNotesUrl: https://github.com/muquit/mailsend-go/releases/tag/v1.0.13
ManifestType: defaultLocale
ManifestVersion: 1.12.0
