# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: OpenAI.ChatGPT
PackageVersion: 26.928.3736.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19041.0
InstallerType: msix
UpgradeBehavior: install
FileExtensions:
- csv
- docx
- pptx
- skill
- tsv
- xls
- xlsm
- xlsx
PackageFamilyName: OpenAI.Codex_2p2nqsd0c76g0
Capabilities:
- internetClient
RestrictedCapabilities:
- appLicensing
- runFullTrust
- unvirtualizedResources
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- Publisher: OpenAI
Installers:
- Architecture: x64
  InstallerUrl: https://persistent.oaistatic.com/codex-app-prod/releases/26.928.3736.0/ChatGPT-x64.msix
  InstallerSha256: 36A36149F7004C5D4619A4DF7882931CC0FCCB4D86B065FAE2C49D7B179BFA8D
  SignatureSha256: 702FA1D0173888D464EA0498D47C9668E1C862E05EBCFD2E1C6F02AC0740C78D
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\OpenAI.Codex_26.928.3736.0_x64__2p2nqsd0c76g0'
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
- Architecture: arm64
  InstallerUrl: https://persistent.oaistatic.com/codex-app-prod/releases/26.928.3736.0/ChatGPT-arm64.msix
  InstallerSha256: 5DED7BAC2A4DCFEFFC0BD19DB8AB0FE05FF24DBBFD58552412404149AF950E03
  SignatureSha256: 19A081705D9300C5325AE0CD40F6017B0F339D89059F327F59C639E9B6DA8C10
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\WindowsApps\OpenAI.Codex_26.928.3736.0_arm64__2p2nqsd0c76g0'
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.arm64
ManifestType: installer
ManifestVersion: 1.12.0
